import Head from 'next/head'
import Nav from '../components/Home/Nav'

export default function Home({ info }) {
  console.log(info);
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
        <Nav />
      </div>

      
    </div>
  )
}

export async function getServerSideProps() {
  const info = await fetch('https://jsonkeeper.com/b/1R0K').then(res => res.json())

  return {
    props: {
      info,
    }
  }
}